### ISSUE TITLE
Short and easily rememberable URLs

### ISSUE THREAD

**Issue by h3ndrk** [HULKs/moments#15]
The idea of the QR code only works well with mobile devices with cameras. We should also plan how desktop/laptop devices can easily show the frontend (which?).

**Comment by schmidma** [comment]
Renamed `upload.html` to `index.html` such that the user does only need to enter the secret. Is this short enough?

**Comment by schmidma** [comment]
Yes, it is. the domain would be `moments.rohow.de` to access the upload page
