### ISSUE TITLE
Transparent images need to have a background

### ISSUE THREAD

**Issue by h3ndrk** [HULKs/moments#5]
Otherwise, highlighted images may overlap with other images, which is hard to see.

**Comment by h3ndrk** [comment]
Transparent images have now a background in the frontend but the backend seems to convert transparent images to non-transparent ones with black background. We should keep transparency. Switching labels...

**Comment by schmidma** [comment]
We currently only support JPEG in cache... and jpeg does not support transparency IIRC. We had to switch to a different caching format. Do we really want to do that?

**Comment by h3ndrk** [comment]
Ah, I forgot about that. No, JPEG is a viable format for the cache.
